apiVersion: v2
name: kubeconfig-python
description: A Helm chart deploying kubeconfig-python app

# A chart can be either an 'application' or a 'library' chart.
#
# Application charts are a collection of templates that can be packaged into versioned archives
# to be deployed.
#
# Library charts provide useful utilities or functions for the chart developer. They're included as
# a dependency of application charts to inject those utilities and functions into the rendering
# pipeline. Library charts do not define any templates and therefore cannot be deployed.
type: application

# This is the chart version. This version number should be incremented each time you make changes
# to the chart and its templates, including the app version.
# Versions are expected to follow Semantic Versioning (https://semver.org/)
version: 0.3.0

# This is the version number of the application being deployed. This version number should be
# incremented each time you make changes to the application. Versions are not expected to
# follow Semantic Versioning. They should reflect the version the application is using.
appVersion: 0.4


dependencies:
# helm repo add --ca-file ~/Downloads/ca.crt harivemula-harbor https://harbor.galaxy.env2.k8scloud.cf/chartrepo/library
# helm repo update
# helm install --ca-file ~/Downloads/ca.crt --version 0.4.1 harivemula-harbor/kubeconfigexample-spring --generate-name
- name: kubeconfigexample-spring
  version: ">=0.4.2"
  repository: "@harivemula-harbor"
  condition: kubeconfigexample-spring.enabled
  import-values:
    - child: service
      parent: kubespringex.service
